name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "dev_webpack" ]
  pull_request:
    branches: [ "dev_webpack" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: get docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gotoo123/just4u
      - name: docker-build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          label: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [build]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop just4u
            docker rm just4u
            docker rmi gotoo123/just4u:dev_webpack
            docker pull gotoo123/just4u:dev_webpack
            docker run --name just4u -d -p 9999:80 gotoo123/just4u:dev_webpack
